learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE URLS
app_name = 'basic_app'

urlpatterns = [
    path("register/",views.register,name='register'),
    path("user_login/",views.user_login,name='user_login'),
    path('',views.index, name='index')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')) #basic_app/ is to go to the urls.py to find the urls patterns
]

learning_templates/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path("",views.index,name='index'),
    path("admin/", admin.site.urls),
    path("basic_app/",include('basic_app.urls')),
    path("logout/",views.user_logout,name='logout'),
    path("special/",views.special,name='special')
    
]

learning_templates/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    
    
    # Base that the user has alraedy account with her personal info
    # So with this way you will add new feature for this user
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING) 

    
    #addintional
    # parameter means that is not requred for the user
    portfolio_site = models.URLField(blank=True) 
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)
    
    def _str__(self):
        return self.user.username

learning_templates/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username','email','password' ) # the fields that i want
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic') 

learning_templates/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

#  For login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


@login_required ## with this way we want only the user will be log in and log out
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid(): ### If is new

            # Save User Form to Database
            user = user_form.save()
            print("I'm Here!!!!")
            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            # user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else: ### If is not new then display that this user is already exists
            # One of the forms was invalid if this else gets called. 
            print("I'm Here!!!!")
            print(user_form.errors,profile_form.errors) 

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})



def user_login(request):
    
    if request.method == 'POST':
        
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)
        print(password)
        #### this method authedicate the user in one line.
        #### create an object of the user and is an authedication  way that check 
        ####the user credentials from database.
        user = authenticate(request,username = username , password = password)
        # print(user.is_authenticated)

        if user is not None:
            print("user is user")
            if user.is_active: # if the sure is active
                print("user is not active")

                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('someone tried to login and failed')
            print(f'Username: {username} and password: {password}')
            return render(request, 'basic_app/login.html',{'error_message': 'Invalid login details'})
    
    else:
        return render(request,'basic_app/login.html',{})



















            
            
            
        

learning_templates/templates/basic_app/base.html
<!DOCTYPE html> 
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> 
  </head>
  <body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
        {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
        {% endif %}
    </ul>
  </div>
</nav>
    
    <!--<div class="container">-->
    {%block body_block%}
    <div class="container">
    </div>

    <!-- enything outside of this will be inherited if you extend! -->
    {% endblock %}
    <!--</div>-->
    
  </body>
</html>

learning_templates/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Django Level Five<h1>
    
</div>
{% endblock %}

learning_templates/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_block %}
  <div class="jumbotron">
      <h1>Please Login</h1>

      <form enctype="multipart/form-data" action="{% url 'basic_app:user_login' %}" method="POST">
        {% csrf_token %} <!-- every form needs the this token for secure reasons-->
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        
        <label for="password">Password:</label>
        <input type="password" name="password">
        
        <input type="submit" name="" value="Login" method="">
      </form>
    
    {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}
    </div>
{% endblock %}

learning_templates/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Register Here</h1>
      <h3>Just fill out the form.</h3>

      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register" method="GET">
      </form>

    {% endif %}


</div>
{% endblock %}